version: '3'

services:
  django_blog_postgresql:
    image: postgres
    container_name: django_blog_postgresql
    volumes:
      - django_blog_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - django_blog_network

volumes:
  django_blog_postgresql:
    external: true
networks:
  django_blog_network:
    external: true